image: docker.io/python:3-alpine

before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt

unittest:
        script:
                - python manage.py test

coverage:
        stage: deploy
        script:
                - pip install -U coverage
                - coverage run  --branch --concurrency=thread --omit='/usr/local/*','.env/*',manage.py  manage.py test
                - coverage report


