cache:
  paths:
    - /app/.coverage

include:
  - template: Auto-DevOps.gitlab-ci.yml

.auto-deploy:
  image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v1.1.0

pages:
  image: python:alpine
  stage: deploy
  needs: ["test"]
  script:
    - df -h
    - pip install coverage
    - cd /cache
    - ls -1A
    - coverage html -d public
    - cd ${OLDPWD}
    - mv /cache/public .
  artifacts:
    paths:
      - public

#- pip install --upgrade pip
#- pip install coverage
#- pip install -r requirements.txt
#- pip install -r requirements-test.txt
