cache:
  paths:
    - .coverage

include:
  - template: Auto-DevOps.gitlab-ci.yml

.auto-deploy:
  image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v1.1.0

pages:
  image: alpine:latest
  stage: deploy
  needs: ["test"]
  script:
    - printenv
    - pwd
    - df -h
    - ls
    - ls -lR public
  artifacts:
    paths:
      - public

#- pip install --upgrade pip
#- pip install coverage
#- pip install -r requirements.txt
#- pip install -r requirements-test.txt
