cache:
  paths:
    - .coverage

include:
  - template: Auto-DevOps.gitlab-ci.yml

.auto-deploy:
  image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v1.1.0

pages:
  image: python:alpine
  stage: deploy
  needs: ["test"]
  script:
    - pip install --upgrade pip
    - pip install coverage
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - coverage html --dir=public
  artifacts:
    paths:
      - public
