cache:
  paths:
    - .coverage

include:
  - template: Auto-DevOps.gitlab-ci.yml

.auto-deploy:
  image: registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:v1.1.0

pages:
  stage: deploy
  script:
    - pip install coverage
    - coverage html --dir=public
  artifacts:
    paths:
      - public
