# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phylum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
