# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clades', '0002_phylum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kingdom',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='phylum',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='kingdom',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phylum',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
